FROM ubuntu:focal-20230126

VOLUME /jupyterhub/.

RUN apt-get update && \
    apt-get install -y npm nodejs python3 python3-pip git nano

RUN python3 -m pip install jupyterhub notebook jupyterlab

RUN npm install -g configurable-http-proxy
RUN cd /home && \
       git clone https://github.com/jupyterhub/nativeauthenticator.git && \
       cd nativeauthenticator && \
       pip3 install -e . && \
       mkdir /etc/jupyterhub && \ 
       cd /etc/jupyterhub && \ 
       jupyterhub --generate-config -f jupyterhub_config.py

RUN nano jupyterhub_config.py
RUN jupyterhub -f /etc/jupyterhub/jupyterhub_config.py